/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2021 Google LLC.
 */
#ifndef __TPUV2_IOCTL_H__
#define __TPUV2_IOCTL_H__ 
#ifdef __KERNEL__
#include <linux/google/gasket.h>
#endif
#include <linux/ioctl.h>
#ifndef __KERNEL__
#include <stdint.h>
#endif
#define TPUV2_NUM_BARS 3
#define TPUV2_TN_BAR_INDEX 2
#define TPUV2_LBUS_BAR_INDEX 0
#define TPUV2_PAGE_SHIFT 12
#define TPUV2_PAGE_SIZE (1 << TPUV2_PAGE_SHIFT)
#define TPUV2_EXTENDED_SHIFT 63
#define TPUV2_ADDR_SHIFT 3
#define TPUV2_LEVEL_SHIFT (TPUV2_PAGE_SHIFT - TPUV2_ADDR_SHIFT)
#define TPUV2_LEVEL_SIZE (1 << TPUV2_LEVEL_SHIFT)
#define TPUV2_PAGE_TABLE_MAX 65536
#define TPUV2_SIMPLE_PAGE_MAX TPUV2_PAGE_TABLE_MAX
#define TPUV2_EXTENDED_PAGE_MAX (TPUV2_PAGE_TABLE_MAX << TPUV2_LEVEL_SHIFT)
#define TPUV2_RESET_RETRY 1200
#define TPUV2_RESET_DELAY 10
#define TPUV2_CHIP_INIT_DONE 2
#define TPUV2_RESET_ACCEPTED 0
#define TPUV2_LBUS_BAR_OFFSET 0x10000000
#define TPUV2_TN_BAR_OFFSET 0
#define TPUV2_NUM_MIRROR_REGISTERS 12
enum tpuv2_reset_types {
 TPUV2_CHIP_REINIT_RESET = 3
};
enum tpuv2_interrupt {
 TPUV2_INTERRUPT_TN0_HBM_WRITE_QUEUE = 0,
 TPUV2_INTERRUPT_TN0_NF_DESCRIPTOR_QUEUE = 1,
 TPUV2_INTERRUPT_TN0_CHIP_DEBUG_QUEUE = 2,
 TPUV2_INTERRUPT_TN0_TC_INFEED_QUEUE = 3,
 TPUV2_INTERRUPT_TN0_EE_INFEED_QUEUE = 4,
 TPUV2_INTERRUPT_TN0_TC_OUTFEED_QUEUE = 5,
 TPUV2_INTERRUPT_TN0_EE_OUTFEED_QUEUE = 6,
 TPUV2_INTERRUPT_TN0_EE_FSM_MICROCODE_QUEUE = 7,
 TPUV2_INTERRUPT_TN0_NF_OUTFEED_QUEUE = 8,
 TPUV2_INTERRUPT_TN0_TC_HOST_0 = 9,
 TPUV2_INTERRUPT_TN0_TC_HOST_1 = 10,
 TPUV2_INTERRUPT_TN0_TC_HOST_2 = 11,
 TPUV2_INTERRUPT_TN0_TC_HOST_3 = 12,
 TPUV2_INTERRUPT_TN0_TC_HALTED = 13,
 TPUV2_INTERRUPT_TN1_HBM_WRITE_QUEUE = 14,
 TPUV2_INTERRUPT_TN1_NF_DESCRIPTOR_QUEUE = 15,
 TPUV2_INTERRUPT_TN1_CHIP_DEBUG_QUEUE = 16,
 TPUV2_INTERRUPT_TN1_TC_INFEED_QUEUE = 17,
 TPUV2_INTERRUPT_TN1_EE_INFEED_QUEUE = 18,
 TPUV2_INTERRUPT_TN1_TC_OUTFEED_QUEUE = 19,
 TPUV2_INTERRUPT_TN1_EE_OUTFEED_QUEUE = 20,
 TPUV2_INTERRUPT_TN1_EE_FSM_MICROCODE_QUEUE = 21,
 TPUV2_INTERRUPT_TN1_NF_OUTFEED_QUEUE = 22,
 TPUV2_INTERRUPT_TN1_TC_HOST_0 = 23,
 TPUV2_INTERRUPT_TN1_TC_HOST_1 = 24,
 TPUV2_INTERRUPT_TN1_TC_HOST_2 = 25,
 TPUV2_INTERRUPT_TN1_TC_HOST_3 = 26,
 TPUV2_INTERRUPT_TN1_TC_HALTED = 27,
 TPUV2_INTERRUPT_ERROR = 28,
 TPUV2_INTERRUPT_LINK = 29,
 TPUV2_INTERRUPT_COUNT = 30,
 TPUV3_INTERRUPT_TN0_EE_HOST_0 = 30,
 TPUV3_INTERRUPT_TN0_EE_HOST_1 = 31,
 TPUV3_INTERRUPT_TN0_EE_HOST_2 = 32,
 TPUV3_INTERRUPT_TN0_EE_HOST_3 = 33,
 TPUV3_INTERRUPT_TN1_EE_HOST_0 = 34,
 TPUV3_INTERRUPT_TN1_EE_HOST_1 = 35,
 TPUV3_INTERRUPT_TN1_EE_HOST_2 = 36,
 TPUV3_INTERRUPT_TN1_EE_HOST_3 = 37,
 TPUV3_INTERRUPT_COUNT = 38
};
struct tpuv2_tc_csr_access {
 int tensor_node;
 int enable;
};
#define TPUV2_IOCTL_BASE 0x7F
#define TPUV2_IOCTL_SET_DEBUG_TC_CSR_ACCESS \
 _IOW(TPUV2_IOCTL_BASE, 1, struct tpuv2_tc_csr_access)
#endif
