# Colab notebooks for Cloud TPU users.

package(
    default_applicable_licenses = ["//third_party/cloud_tpu:license"],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files(glob([
    "*.ipynb",
]))
