/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2021 Google LLC.
 */
#ifndef _DRIVERS_CHAR_TPU_COMMON_TPUV4LITE_TPUV4LITE_H_
#define _DRIVERS_CHAR_TPU_COMMON_TPUV4LITE_TPUV4LITE_H_ 
#define TPUV4LITE_LBUS_BAR_INDEX 0x0
#define TPUV4LITE_LBUS_BAR_OFFSET 0x0
#define TPUV4LITE_LBUS_BAR_BYTES 0x4000000
#define TPUV4LITE_CSR_BAR_INDEX 0x2
#define TPUV4LITE_CSR_BAR_OFFSET 0x10000000
#define TPUV4LITE_CSR_BAR_BYTES 0x80000000
#define TPUV4LITE_RESET_RETRY 1200
#define TPUV4LITE_RESET_DELAY 10
#define TPUV4LITE_CHIP_INIT_DONE 1
#define TPUV4LITE_RESET_ACCEPTED 0
enum tpuv4lite_reset_types { TPUV4LITE_CHIP_REINIT_RESET = 1 };
#endif
