KERNELDIR ?= /lib/modules/$(shell uname -r)/build
PWD = $(shell pwd)
EXTRA_CFLAGS = -I$(PWD)/include -I$(PWD)/include/uapi -I$(PWD)

export CONFIG_HW_ACCEL = m
export CONFIG_GASKET_FRAMEWORK = m
export CONFIG_TPU_COMMON_COMMON = m
export CONFIG_TPU_V1_CORE = m
export CONFIG_TPU_V2_DRIVER = m
export CONFIG_TPU_V1_DRIVER = m

all:
	$(MAKE) -C $(KERNELDIR) M=$(PWD)/drivers/accel \
		EXTRA_CFLAGS="$(EXTRA_CFLAGS)" modules
	$(MAKE) -C $(KERNELDIR) M=$(PWD)/drivers/gasket \
		EXTRA_CFLAGS="$(EXTRA_CFLAGS)" \
		KBUILD_EXTRA_SYMBOLS="$(PWD)/drivers/accel/Module.symvers" \
		modules
	$(MAKE) -C $(KERNELDIR) M=$(PWD)/drivers/char/tpu_common \
		EXTRA_CFLAGS="$(EXTRA_CFLAGS)" \
		KBUILD_EXTRA_SYMBOLS="$(PWD)/drivers/gasket/Module.symvers" \
		modules
	find . -name "*.ko" -exec cp -f '{}' . ';'

clean:
	$(MAKE) -C $(KERNELDIR) M=$(PWD)/drivers/accel clean
	$(MAKE) -C $(KERNELDIR) M=$(PWD)/drivers/gasket clean
